# Обучение классических моделей

In [1]:
import pandas as pd
import sklearn as sk

Прочитаем данные с отмасштабированными признаками

In [2]:
X_train_scaled = pd.read_csv('data/X_train_scaled.csv')
X_test_scaled = pd.read_csv('data/X_test_scaled.csv')
y_train = pd.read_csv('data/y_train.csv').values.flatten() # так как методы fit принимают одномерный массив, а у нас здесь df
y_test = pd.read_csv('data/y_test.csv').values.flatten()

In [3]:
X_train_scaled.head(3)

,age,education.num,capital.gain,capital.loss,hours.per.week,workclass_Local-gov,workclass_Never-worked,workclass_Private,workclass_Self-emp-inc,workclass_Self-emp-not-inc,...,relationship_Own-child,relationship_Unmarried,relationship_Wife,race_Asian-Pac-Islander,race_Black,race_Other,race_White,sex_Male,is_usa_no,is_usa_yes
0,1.498786,1.520923,-0.145313,-0.215487,-0.031025,-0.261482,-0.013856,-1.520489,-0.186659,-0.288699,...,-0.430770,-0.341955,-0.224987,-0.181306,-0.324388,-0.091868,0.412008,0.700541,-0.305685,0.33978
1,-1.138419,-0.422173,-0.145313,-0.215487,-0.031025,-0.261482,-0.013856,0.657683,-0.186659,-0.288699,...,2.321424,-0.341955,-0.224987,-0.181306,-0.324388,-0.091868,0.412008,0.700541,-0.305685,0.33978
2,1.352274,-0.033554,0.893630,-0.215487,0.374998,-0.261482,-0.013856,0.657683,-0.186659,-0.288699,...,-0.430770,-0.341955,-0.224987,-0.181306,-0.324388,-0.091868,0.412008,0.700541,-0.305685,0.33978

## BaseLine (const)

In [4]:
from sklearn.dummy import DummyClassifier
from sklearn.metrics import f1_score, accuracy_score, precision_score, recall_score

In [5]:
Dummy_clf = DummyClassifier(strategy='most_frequent', random_state=52)

In [6]:
Dummy_clf.fit(X_train_scaled, y_train)

DummyClassifier(random_state=52, strategy='most_frequent')

In [7]:
y_pred = Dummy_clf.predict(X_test_scaled)

Посчитаем метрики для нашей baseline модели, целевая метрика - f1-macro, но будем считать ещё accuracy, precision и recall для анализа предсказаний модели, хуже от этого точно не будет

In [8]:
f1 = f1_score(y_test, y_pred, average='macro', zero_division=0)
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, zero_division=0)
recall = recall_score(y_test, y_pred, zero_division=0)

In [9]:
metrics_const = pd.DataFrame(
    columns=['f1-macro', 'accuracy', 'precision', 'recall'],
    data=[[f1, accuracy, precision, recall]],
    index=['Const']
)

In [10]:
metrics_const

       f1-macro  accuracy  precision  recall
Const  0.434586  0.768617        0.0     0.0

## LogReg

In [11]:
from sklearn.linear_model import LogisticRegression

In [12]:
logreg = LogisticRegression(random_state=52, class_weight='balanced')

In [13]:
logreg.fit(X_train_scaled, y_train)

LogisticRegression(class_weight='balanced', random_state=52)

In [14]:
y_pred_logreg = logreg.predict(X_test_scaled)

In [15]:
f1_logreg = f1_score(y_test, y_pred_logreg, average='macro')
accuracy_logreg = accuracy_score(y_test, y_pred_logreg)
precision_logreg = precision_score(y_test, y_pred_logreg)
recall_logreg = recall_score(y_test, y_pred_logreg)

In [16]:
metrics_logreg = pd.DataFrame(
    columns=['f1-macro', 'accuracy', 'precision', 'recall'],
    data=[[f1_logreg, accuracy_logreg, precision_logreg, recall_logreg]],
    index=['LogReg']
)

In [17]:
metrics_logreg

        f1-macro  accuracy  precision    recall
LogReg   0.76582   0.80562   0.551917  0.850033

## Random Forest

Тут будем использовать данные без масштабирования числовых признаков

In [18]:
X_train_encoded = pd.read_csv('data/X_train_encoded.csv')
X_test_encoded = pd.read_csv('data/X_test_encoded.csv')

In [19]:
from sklearn.ensemble import RandomForestClassifier

In [20]:
rf = RandomForestClassifier(random_state=52, class_weight='balanced', n_estimators=500, max_depth=20, min_samples_split=10, min_samples_leaf=5)

In [21]:
rf.fit(X_train_encoded, y_train)

RandomForestClassifier(class_weight='balanced', max_depth=20,
                       min_samples_leaf=5, min_samples_split=10,
                       n_estimators=500, random_state=52)

In [22]:
y_pred_rf = rf.predict(X_test_encoded)

In [23]:
f1_rf = f1_score(y_test, y_pred_rf, average='macro')
accuracy_rf = accuracy_score(y_test, y_pred_rf)
precision_rf = precision_score(y_test, y_pred_rf)
recall_rf = recall_score(y_test, y_pred_rf)

In [24]:
metrics_rf = pd.DataFrame(
    columns=['f1-macro', 'accuracy', 'precision', 'recall'],
    data=[[f1_rf, accuracy_rf, precision_rf, recall_rf]],
    index=['Random Forest']
)

In [25]:
metrics_rf

               f1-macro  accuracy  precision    recall
Random Forest  0.774987  0.813143   0.562392  0.867286

## SVM

Тут необходимо использовать отмасштабированные числовые признаки

In [26]:
svm = sk.svm.SVC(random_state=52, class_weight='balanced', kernel='rbf', C=1, gamma='scale')

In [27]:
svm.fit(X_train_scaled, y_train)

SVC(C=1, class_weight='balanced', random_state=52)

In [28]:
y_pred_svm = svm.predict(X_test_scaled)

In [29]:
f1_svm = f1_score(y_test, y_pred_svm, average='macro')
accuracy_svm = accuracy_score(y_test, y_pred_svm)
precision_svm = precision_score(y_test, y_pred_svm)
recall_svm = recall_score(y_test, y_pred_svm)

In [30]:
metrics_svm = pd.DataFrame(
    columns=['f1-macro', 'accuracy', 'precision', 'recall'],
    data=[[f1_svm, accuracy_svm, precision_svm, recall_svm]],
    index=['SVM']
)

In [31]:
metrics_svm

     f1-macro  accuracy  precision    recall
SVM  0.763145  0.801474   0.544845  0.862641

## KNN

Тут также тспользуем отмасштабированные числовые признаки

In [32]:
knn = sk.neighbors.KNeighborsClassifier(n_neighbors=7)

In [33]:
knn.fit(X_train_scaled, y_train)

KNeighborsClassifier(n_neighbors=7)

In [34]:
y_pred_knn = knn.predict(X_test_scaled)

In [35]:
f1_knn = f1_score(y_test, y_pred_knn, average='macro')
accuracy_knn = accuracy_score(y_test, y_pred_knn)
precision_knn = precision_score(y_test, y_pred_knn)
recall_knn = recall_score(y_test, y_pred_knn)

In [36]:
metrics_knn = pd.DataFrame(
    columns=['f1-macro', 'accuracy', 'precision', 'recall'],
    data=[[f1_knn, accuracy_knn, precision_knn, recall_knn]],
    index=['KNN']
)

In [37]:
metrics_knn

     f1-macro  accuracy  precision    recall
KNN  0.771803  0.843237   0.678414  0.613139

## CatBoost

Для catboost будем использовать заранее подготовленные данные без кодирования признаков и масштабирования, catboost сам отлично сделает это

In [38]:
X_train_raw = pd.read_csv('data/X_train_raw.csv')
X_test_raw = pd.read_csv('data/X_test_raw.csv')

In [39]:
cat_cols = X_train_raw.select_dtypes(include='str').columns.tolist()

In [40]:
import catboost

In [41]:
model = catboost.CatBoostClassifier(random_seed=52, class_weights=[1, 3], verbose=0, learning_rate=0.1, depth=6, iterations=1000)

In [42]:
model.fit(X_train_raw, y_train, cat_features=cat_cols)

In [43]:
y_pred = model.predict(X_test_raw)

In [44]:
f1_cat = f1_score(y_test, y_pred, average='macro')
accuracy_cat = accuracy_score(y_test, y_pred)
precision_cat = precision_score(y_test, y_pred)
recall_cat = recall_score(y_test, y_pred)

In [45]:
metrics_cat = pd.DataFrame(
    columns=['f1-macro', 'accuracy', 'precision', 'recall'],
    data=[[f1_cat, accuracy_cat, precision_cat, recall_cat]],
    index=['CatBoost']
)

In [46]:
metrics_cat

          f1-macro  accuracy  precision   recall
CatBoost  0.795522   0.83556   0.602637  0.84937

## Итог

Сводная таблица метрик для всех моделей

In [47]:
metrics_all_models = pd.concat([metrics_const, metrics_logreg, metrics_rf, metrics_svm, metrics_knn, metrics_cat])

In [48]:
metrics_all_models

               f1-macro  accuracy  precision    recall
Const          0.434586  0.768617   0.000000  0.000000
LogReg         0.765820  0.805620   0.551917  0.850033
Random Forest  0.774987  0.813143   0.562392  0.867286
SVM            0.763145  0.801474   0.544845  0.862641
KNN            0.771803  0.843237   0.678414  0.613139
CatBoost       0.795522  0.835560   0.602637  0.849370